services:
  - type: web
    name: tracking-number-generator-api
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: REDIS_URLx
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
    ipAllowList: []
    maxmemoryPolicy: noeviction